name: transform-feed
on:
  issue_comment:
    types: [created]
  repository_dispatch:
        types: [build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate comment and issue number
      if: ${{ github.event.comment.body != 'build' || github.event.issue.number != 1 }}
      run: make phony-error
      
    - name: Add start reaction
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: eyes

    - name: Install deps
      run: make install

    - name: Fetch and parse feed
      run: make feed username=${{ secrets.ANCHOR_USERNAME }} site-base=${{ secrets.SITE_BASE }}

    - name: Feed to json
      run: make transform

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Actions"
        rm -rf Makefile bin tmp ops *.clj *.md .github
        git add public/*
        git commit -am ":loudspeaker: Feed update requested by ${{ github.event.comment.user.login }}" || echo "No new updates".

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: gh-pages

    - name: Add success reaction
      uses: peter-evans/create-or-update-comment@v1
      if: ${{ success() }}
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: heart

    - name: Add generic fail reaction
      uses: peter-evans/create-or-update-comment@v1
      # Send fail responses only on issue number 1
      if: ${{ failure() && github.event.issue.number == 1 }}
      with:
        comment-id: ${{ github.event.comment.id }}     
        reactions: -1
        
        
    - name: Create error comment
      uses: peter-evans/create-or-update-comment@v1
      if: ${{ failure() && github.event.issue.number == 1 }}
      with:
        issue-number: 1
        body: |
          ðŸ¤–
          
          I was not able to build the feed. It could be due to multiple reasons: 
          - Make sure the required secrets: **ANCHOR_USERNAME** and **SITE_BASE** are present
          - Check the actions pane for any error
          - Read docs or raise an issue


